name: Generate Localized Readme
description: Generates localised readme files for your git
author: mrf0rtuna4
branding:
  icon: 'cloud-lightning'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
