name: "generate-readme-localed-files"
description: "Generates localised readmi files for your git"
author: "mrf0rtuna4"

runs:
  using: python

inputs:
  github_user_name:
    description: "github user name"
    required: true
  github_token:
    description: "github token used to fetch the contribution calendar. Default to the action token if empty."
    required: false
    default: ${{ github.token }}
  outputs:
    required: false
    description: |
      list of files to generate.
      one file per line. Each output can be customized with options as query string.
