name: Translate README
on:
  schedule:
    - cron: '0 */2124 * * *'
  
  workflow_dispatch:
  
  push:
    branches:
    - master

jobs:
  translate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run translation
        env:
          GITHUB_TOKEN: ${{ secrets.GTK }}
          LANGS: 'serbian, italian, kazakh, english'
        run: python core/translator.py

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: translations
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GTK }}
