name: Translate README
on:
  schedule:
    - cron: "0 */2124 * * *" 
  
  workflow_dispatch:
  
  push:
    branches:
    - master

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run translation
        env:
          GITHUB_TOKEN: ${{ secrets.GTK }}
        run: python core/translate.py

      - name: Push to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GTK }}
          USER: mrf0rtuna4/mrf0rtuna4
        run: python core/push_to_git.py
